---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: sbr-agent
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: sbr-operator
    app.kubernetes.io/managed-by: sbr-operator
  name: sbr-agent
  namespace: system
automountServiceAccountToken: true 