apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: sbr-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: StorageBasedRemediationConfig is the Schema for the storagebasedremediationconfigs API.
      displayName: StorageBasedRemediationConfig
      kind: StorageBasedRemediationConfig
      name: storagebasedremediationconfigs.storage-based-remediation.medik8s.io
      version: v1alpha1
    - description: StorageBasedRemediation is the Schema for the storagebasedremediations API.
      displayName: StorageBasedRemediation
      kind: StorageBasedRemediation
      name: storagebasedremediations.storage-based-remediation.medik8s.io
      version: v1alpha1
    - description: StorageBasedRemediationTemplate is the Schema for the storagebasedremediationtemplates
        API.
      displayName: StorageBasedRemediation Template
      kind: StorageBasedRemediationTemplate
      name: storagebasedremediationtemplates.storage-based-remediation.medik8s.io
      version: v1alpha1
  description: TBD
  displayName: Storage Based Remediation
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - sbr
  - storage
  - remediation
  links:
  - name: SBR Operator
    url: https://medik8s.io
  maintainers:
  - email: medik8s@googlegroups.com
    name: Medik8s Team
  maturity: alpha
  provider:
    name: medik8s
  version: 0.0.0
