## Append samples of your project ##
resources:
- storage-based-remediation_v1alpha1_sbdremediation.yaml
- storage-based-remediation_v1alpha1_storagebasedremediationtemplate.yaml
- storage-based-remediation_v1alpha1_sbdconfig.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
