# Alternative NFS Storage Configuration for SBD Cache Coherency
# Use this instead of EFS CSI driver when you need explicit cache coherency controls
#
# This configuration uses the Standard NFS CSI driver (nfs.csi.k8s.io) 
# which supports cache=none, sync, and local_lock=none mount options
# required for proper SBD operation.

---
# Install Standard NFS CSI Driver
# kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/deploy/install-driver.yaml

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sbd-nfs-coherent
  labels:
    app.kubernetes.io/managed-by: sbd-operator
provisioner: nfs.csi.k8s.io
parameters:
  # Use your EFS DNS name as the NFS server
  server: fs-03af5af5e88a8d0d6.efs.ap-southeast-2.amazonaws.com
  share: /sbd
mountOptions:
  # Critical SBD cache coherency options
  - nfsvers=4.1        # Use NFSv4.1 for best performance
  - cache=none         # ✅ Disable client-side caching - critical for SBD
  - sync               # ✅ Force synchronous operations - critical for SBD
  - local_lock=none    # ✅ Use server-side locking - critical for SBD
  
  # Performance and reliability options
  - hard               # Hard mount for reliability
  - timeo=600          # 60 second timeout
  - retrans=2          # 2 retries before recovery
  - rsize=1048576      # 1MB read size for performance
  - wsize=1048576      # 1MB write size for performance
  
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate

---
# Test PVC using the new StorageClass
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-sbd-nfs-coherent
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: sbd-nfs-coherent
  resources:
    requests:
      storage: 1Gi

---
# Test pod to verify mount options
apiVersion: v1
kind: Pod
metadata:
  name: test-sbd-nfs-mount
  namespace: default
spec:
  containers:
  - name: test-container
    image: busybox:1.35
    command: 
    - sh
    - -c
    - |
      echo "=== NFS Mount Information ==="
      mount | grep /mnt/sbd
      echo ""
      echo "=== Testing SBD Cache Coherency ==="
      echo "test-$(date)" > /mnt/sbd/test-file
      sync
      cat /mnt/sbd/test-file
      echo ""
      echo "=== File Locking Test ==="
      flock /mnt/sbd/test-lock echo "File locking works!"
      echo ""
      echo "Sleeping for troubleshooting..."
      sleep 3600
    volumeMounts:
    - name: sbd-storage
      mountPath: /mnt/sbd
  volumes:
  - name: sbd-storage
    persistentVolumeClaim:
      claimName: test-sbd-nfs-coherent
  restartPolicy: Never

---
# Updated SBDConfig to use the new StorageClass
apiVersion: medik8s.medik8s.io/v1alpha1
kind: SBDConfig
metadata:
  name: sbd-config-nfs-coherent
  namespace: default
spec:
  imagePullPolicy: Always
  iotimeout: 5s
  logLevel: debug
  peerCheckInterval: 5s
  petIntervalMultiple: 4
  rebootMethod: none
  sbdTimeoutSeconds: 30
  sbdUpdateInterval: 5s
  sbdWatchdogPath: /dev/watchdog
  sharedStorageClass: sbd-nfs-coherent  # Use the new coherent StorageClass
  staleNodeTimeout: 2h0m0s
  watchdogTimeout: 1m30s 