apiVersion: storage-based-remediation.medik8s.io/v1alpha1
kind: StorageBasedRemediationConfig
metadata:
  name: test-storagebasedremediationconfig
spec:
  namespace: sbr-system
  sbrWatchdogPath: /dev/watchdog

